### PR TITLE
adding support for epel based systems.

### PR DESCRIPTION
**Pull request by majormoses**
Should now support:
- apt repo
- yum repo
- systemd
- upstart
- init.d

### CODE REVIEW

**Comment by majormoses** [comment]
fixes: https://github.com/Netuitive/chef-netuitive/issues/4

@Createor 
We should discuss centos first before merging this as the epel package installs service as init.d rather than upstart. This is overwritable via the attributes in the lwrp (not chef attributes) so it can work if needed with centos. I might be opinionated in assuming the order of preference should be systemd -> upstart -> init.d and would like your feedback.

**Comment by majormoses** [comment]
btw this will work with centos7 as it uses systemd

**Comment by Grumblesmith** [comment]
I believe that's a fair question, but will need to defer to @shawnbutts to comment on why we install the agent service to init.d.

**Comment by shawnbutts** [comment]
While upstart is available on CentOS 6, it is not widely used since init.d is also available and was standard more many previous releases.  CentOS 7 switched to SystemD like many other distros.

Since the package installer already detects and used the most appropriate init system, why is  "init_command" required?

**Comment by majormoses** [comment]
@shawnbutts I can try without but it did not work for me when I started writing it. Its possible that this is a non issue and could have been attributed to many things. Though one could argue that this functionality is desired since it allows overwriting as the user wants (ubuntu 15.04 supports systemd, upstart, and init.d) and maybe there might be reasons to overwrite...

Either way I am going to test removing it and see what happens...

**Comment by shawnbutts** [comment]
While I do see the possible benefit of allowing the user to choose, it would make modifications to the scripts more difficult during upgrades.

If it helps, here's the script that is run during the package install to figure out which script to install.

https://github.com/Netuitive/omnibus-netuitive-agent/blob/master/package-scripts/netuitive-agent/postinst

Thank you for all your work on this.  It is much appreciated.

**Comment by majormoses** [comment]
@shawnbutts I ran some quick tests and it looks like we can get by without it. I am kind of torn on this but when writing community cookbooks you should follow the vendors defaults...

**Comment by majormoses** [comment]
I will update the pr shortly, I will leave the functionality in but commented out in case we ever decide to change our stance...unless you guys feel otherwise...

**Comment by majormoses** [comment]
I changed my stance, I will remove the stuff from the lwrps, recipes, and attribute. I will leave the helper functions since they could be useful for other reasons

**Comment by majormoses** [comment]
@Createor @shawnbutts ready for review

**Pull request merged**
